# This is a basic workflow to help you get started with Actions

name: msm-Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push: 
    branches: [main]
  pull_request: 
    branches: [main]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Image Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install required packages
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install python3.10
          sudo apt install -y uuid-dev clang llvm gcc-aarch64-linux-gnu
          export CLANG38_BIN=/usr/lib/llvm-38/bin/ && export CLANG38_AARCH64_PREFIX=aarch64-linux-gnu-
          pip install --upgrade -r ./pip-requirements.txt
          
      - name: UEFI build (Epsilon)
        run: |
          chmod +x ./build_uefi_epsilon.sh && ./build_uefi_epsilon.sh
        
      - name: UEFI boot image build
        run: |
          chmod +x ./build_boot_images.sh && ./build_boot_images.sh
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with: # Artifact name
          name: SM8150 UEFI
          # A file, directory or wildcard pattern that describes what to upload
          path: ./ImageResources/*/uefi.img
